Adding gcov/lcov coverage report to configure and makefile.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -658,6 +658,8 @@ ac_ct_CC
 CCDEPMODE
 am__fastdepCC_TRUE
 am__fastdepCC_FALSE
+GCOV_TRUE
+GCOV_FALSE
 CPPUNIT_CONFIG
 CPPUNIT_CFLAGS
 CPPUNIT_LIBS
@@ -1254,6 +1256,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --enable-gcov           enable test coverage with gcov [default=no]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3772,6 +3775,36 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
 
 # Checks for typedefs, structures, and compiler characteristics.
 
+# Check whether to enable gcov coverage flags and macros
+
+# Check whether --enable-gcov was given.
+if test "${enable_gcov+set}" = set; then
+  enableval=$enable_gcov; case "${enableval}" in
+         yes) gcov=true ;;
+         no)  gcov=false ;;
+         *)   { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-gcov" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-gcov" >&2;}
+   { (exit 1); exit 1; }; } ;;
+         esac
+else
+  gcov=false
+fi
+
+
+ if test x"$gcov" = "xtrue"; then
+  GCOV_TRUE=
+  GCOV_FALSE='#'
+else
+  GCOV_TRUE='#'
+  GCOV_FALSE=
+fi
+
+
+if test x"$gcov" = "xtrue"; then
+    CFLAGS="$CFLAGS -fprofile-arcs -ftest-coverage"
+    CXXFLAGS="$CXXFLAGS -fprofile-arcs -ftest-coverage"
+fi
+
 # check whether cppunit is available
 
 
@@ -4072,6 +4105,13 @@ if test -z "${am__fastdepCC_TRUE}" && test -z "${am__fastdepCC_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCC\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCC\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${GCOV_TRUE}" && test -z "${GCOV_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GCOV\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GCOV\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -4679,6 +4719,8 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 CCDEPMODE!$CCDEPMODE$ac_delim
 am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
 am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
+GCOV_TRUE!$GCOV_TRUE$ac_delim
+GCOV_FALSE!$GCOV_FALSE$ac_delim
 CPPUNIT_CONFIG!$CPPUNIT_CONFIG$ac_delim
 CPPUNIT_CFLAGS!$CPPUNIT_CFLAGS$ac_delim
 CPPUNIT_LIBS!$CPPUNIT_LIBS$ac_delim
@@ -4688,7 +4730,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 88; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 90; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
